# This is the database schema file for doctrine
# (defines tables and relations of the ontology)
#
# doctrine reads this file, creates the orm models
# for database access and creates the tables in the
# database
#
# read more about yml schemes for doctrine here
# http://www.doctrine-project.org/projects/orm/1.2/docs/manual/yaml-schema-files/en

options:
  collation: utf8_general_ci
  charset: utf8
  type: InnoDB

# definition of the table that holds
# the object properties of ontology
Objectproperty:
  columns:
    id:
      type: integer(8)
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    label:
      type: string(255)
      notnull: true
    rangename:
      type: string(255)
  options:
    type: MEMORY

# definition of the table that holds
# the datatype properties of ontology
Datatypeproperty:
  columns:
    id:
      type: integer(8)
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    label:
      type: string(255)
      notnull: true
    rangename:
      type: string(255)
      notnull: true
  options:
    type: MEMORY

# definition of the table that holds
# the datatypes of the ontology
Datatype:
  columns:
    id:
      type: integer(8)
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    label:
      type: string(255)
      notnull: true
  options:
    type: MEMORY

# definition of the table that holds
# the ontology classes
# including nested set behavior
Ontologyclass:
  actAs:
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
  columns:
    id:
      type: integer(8)
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    label:
      type: string(255)
      notnull: true
  relations:
    Objectproperties:
      class: Objectproperty
      refClass: OntologyclassObjectproperty
      foreignAlias: Ontologyclasses
    Datatypeproperties:
      class: Datatypeproperty
      refClass: OntologyclassDatatypeproperty
      foreignAlias: Ontologyclasses
  options:
    type: MEMORY

# cross table for n:m relations of
# ontology classes and datatype
# properties
OntologyclassDatatypeproperty:
  columns:
    ontologyclass_id:
      type: integer(8)
      unsigned: true
      primary: true
      notnull: true
    datatypeproperty_id:
      type: integer(8)
      unsigned: true
      primary: true
      notnull: true
  relations:
    Ontologyclass:
      foreignAlias: OntologyclassDatatypeproperties
    Datatypeproperty:
      foreignAlias: OntologyclassDatatypeproperties
  options:
    type: MEMORY

# cross table for n:m relations of
# ontology classes and object
# properties
OntologyclassObjectproperty:
  columns:
    ontologyclass_id:
      type: integer(8)
      unsigned: true
      primary: true
      notnull: true
    objectproperty_id:
      type: integer(8)
      unsigned: true
      primary: true
      notnull: true
  relations:
    Ontologyclass:
      foreignAlias: OntologyclassObjectproperties
    Objectproperty:
      foreignAlias: OntologyclassObjectproperties
  options:
    type: MEMORY